inherit_from:
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - '**/*~'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'provisioning/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails:
  Enabled: true

# TODO: re-enable when we're on Rails 5
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/HttpPositionalArguments
Rails/HttpPositionalArguments:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Lambda:
  EnforcedStyle: lambda

# RSpec's `include` method causes this to false-positive
Style/MixinGrouping:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockChain:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
